# Generated by Django 5.2.9 on 2025-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabi', '0002_syllabus_is_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='academic_integrity_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='additional_literature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='appendix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='assessment_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='class_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='contact_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='course_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='credits_ects',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='delivery_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='grading_scale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='inclusive_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructor_contacts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='main_literature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='program_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='self_study_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='teaching_methods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='teaching_philosophy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='total_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='literature_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabustopic',
            name='week_label',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='main_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kz', 'Казахский'), ('en', 'English')], default='ru', max_length=5),
        ),
    ]
